version: '3'
services:
  playground:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - '8888:8888'
    volumes:
      - experiments:/quantum-power-system-state-estimation

  test:
    build:
      context: .
      dockerfile: docker/dev.dockerfile

volumes:
  experiments: